name: Java CI

 

on: [push]

 

jobs:
  build:
    runs-on: ubuntu-latest

 

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Install Newman to run REST API test
        run: npm install -g newman    
          
      - name: Create the JAR file with Maven
        run: mvn -B package 
        
      - name: Run Postman REST API tests
        run: newman run src/test/java/com/album/albumrater/AlbumraterAPI.postman_collection.json
